PACKAGE_NAME="hpsa-dkms"
PACKAGE_VERSION="1.0"
BUILT_MODULE_NAME[0]="hpsa"
MAKE[0]="make"
DEST_MODULE_LOCATION[0]="/kernel/drivers/scsi"
AUTOINSTALL="yes"
BUILD_EXCLUSIVE_KERNEL="^6\.17\.[0-9]+\-[0-9]+\-pve$"
